### ISSUE TITLE
Error 1.21.1

### ISSUE THREAD

**Issue by flashpaul** [Ajneb97/PaintballBattle#12] opened 2024-09-16 21:22 UTC
![image](https://github.com/user-attachments/assets/ec471617-d0f8-48e5-9141-d7d975824f21)

Error occurring when the server is switched on. The Plugin was already present in previous versions of the server.

**Comment by Bizarrus** [comment] 2024-09-24 20:17
The problem is on [Line #167](https://github.com/Ajneb97/PaintballBattle/blob/7e081bc199f9c6289eb695ab2974c8e112f54025/src/pb/ajneb97/PaintballBattle.java#L155-L169) 
```!java
serverVersion = ServerVersion.valueOf(packageName.replace("org.bukkit.craftbukkit.", ""));
```

`ServerVersion.valueOf` cant find the `enum`-value of the `packageName`.

Please Modify the method to:
```!java
public void setVersion(){
    String packageName = Bukkit.getServer().getClass().getPackage().getName();
    String bukkitVersion = Bukkit.getServer().getBukkitVersion().split("-")[0];
    
    // DEBUG Ausgabe!
    System.out.println("[DEBUG] setVersion: packageName = " + packageName);
    System.out.println("[DEBUG] setVersion: bukkitVersion = " + bukkitVersion);

    switch(bukkitVersion){
        case "1.20.5":
        case "1.20.6":
            serverVersion = ServerVersion.v1_20_R4;
            break;
        case "1.21":
            serverVersion = ServerVersion.v1_21_R1;
            break;
        default:
            /* PROBLEM >>> */ serverVersion = ServerVersion.valueOf(packageName.replace("org.bukkit.craftbukkit.", ""));
    }
}
```

And post the console output of `packageName` and `bukkitVersion`.

I can't test it myself as I haven't bought Minecraft or installed any clients or servers. As an outsider, I can only guide you to the result.

**Comment by Ajneb97** [comment] 2024-09-24 20:27
The plugin is not updated to 1.21.1

**Comment by flashpaul** [comment] 2024-09-29 20:13
Why not?

**Comment by Ajneb97** [comment] 2024-09-30 10:36
Now it is

**Comment by Bizarrus** [comment] 2024-09-30 10:53
Please close the issue, if its fixed

**Closed** 2024-09-30 16:45 UTC
